/**
 * Bảng ký hiệu / mẫu công thức cho hộp thoại chèn công thức (MathDialog).
 * Quy ước: `{}` là ô cần điền — khi chèn, con trỏ đặt vào `{}` đầu tiên; khi hiển thị trên nút, `{}` vẽ thành □.
 * Mỗi mục: [latex, nhãn tiếng Việt (tuỳ chọn, dùng làm tooltip / tên mẫu)].
 * Mọi mục được kiểm tra render được bằng KaTeX (throwOnError) — thêm mục mới thì giữ đúng cú pháp KaTeX hỗ trợ.
 */
export const MATH_CATEGORIES = [
  {
    id: 'basic',
    label: 'Cơ bản',
    items: [
      ['\\frac{}{}', 'Phân số'],
      ['\\dfrac{}{}', 'Phân số cỡ lớn'],
      ['\\sqrt{}', 'Căn bậc hai'],
      ['\\sqrt[{}]{}', 'Căn bậc n'],
      ['{}^{}', 'Luỹ thừa'],
      ['{}_{}', 'Chỉ số dưới'],
      ['{}_{}^{}', 'Chỉ số dưới và trên'],
      ['\\left( {} \\right)', 'Ngoặc tròn tự co giãn'],
      ['\\left[ {} \\right]', 'Ngoặc vuông tự co giãn'],
      ['\\left\\{ {} \\right\\}', 'Ngoặc nhọn tự co giãn'],
      ['\\left| {} \\right|', 'Giá trị tuyệt đối'],
      ['\\left\\| {} \\right\\|', 'Chuẩn (độ dài vector)'],
      ['\\lfloor {} \\rfloor', 'Phần nguyên (làm tròn xuống)'],
      ['\\lceil {} \\rceil', 'Làm tròn lên'],
      ['+', 'Cộng'],
      ['-', 'Trừ'],
      ['\\pm', 'Cộng trừ'],
      ['\\mp', 'Trừ cộng'],
      ['\\times', 'Nhân'],
      ['\\cdot', 'Nhân (chấm)'],
      ['\\div', 'Chia'],
      ['=', 'Bằng'],
      ['\\neq', 'Khác'],
      ['\\approx', 'Xấp xỉ'],
      ['\\equiv', 'Đồng nhất / đồng dư'],
      ['<', 'Nhỏ hơn'],
      ['>', 'Lớn hơn'],
      ['\\le', 'Nhỏ hơn hoặc bằng'],
      ['\\ge', 'Lớn hơn hoặc bằng'],
      ['\\ll', 'Rất nhỏ hơn'],
      ['\\gg', 'Rất lớn hơn'],
      ['\\infty', 'Vô cùng'],
      ['{}^\\circ', 'Độ'],
      ['\\%', 'Phần trăm'],
      ['{}!', 'Giai thừa'],
      ['\\overline{}', 'Gạch trên (trung bình, số phức liên hợp)'],
      ['\\hat{}', 'Mũ trên'],
      ['\\tilde{}', 'Dấu ngã trên'],
      ['\\vec{}', 'Vector'],
      ['\\overrightarrow{}', 'Vector (mũi tên dài)'],
      ['\\dot{}', 'Chấm trên (đạo hàm theo thời gian)'],
      ['\\ddot{}', 'Hai chấm trên'],
      ['\\bar{}', 'Gạch trên (ngắn)'],
      ['\\underline{}', 'Gạch dưới'],
      ['\\overbrace{}^{}', 'Ngoặc nhọn trên'],
      ['\\underbrace{}_{}', 'Ngoặc nhọn dưới'],
      ['\\text{}', 'Chữ thường trong công thức'],
      ['\\quad', 'Khoảng trắng rộng'],
      ['\\,', 'Khoảng trắng hẹp'],
      ['\\cdots', 'Ba chấm giữa'],
      ['\\ldots', 'Ba chấm dưới'],
      ['\\vdots', 'Ba chấm dọc'],
      ['\\ddots', 'Ba chấm chéo'],
    ],
  },
  {
    id: 'greek',
    label: 'Hy Lạp',
    items: [
      ['\\alpha'], ['\\beta'], ['\\gamma'], ['\\delta'], ['\\epsilon'], ['\\varepsilon'], ['\\zeta'], ['\\eta'],
      ['\\theta'], ['\\vartheta'], ['\\iota'], ['\\kappa'], ['\\lambda'], ['\\mu'], ['\\nu'], ['\\xi'],
      ['\\pi'], ['\\varpi'], ['\\rho'], ['\\varrho'], ['\\sigma'], ['\\varsigma'], ['\\tau'], ['\\upsilon'],
      ['\\phi'], ['\\varphi'], ['\\chi'], ['\\psi'], ['\\omega'],
      ['\\Gamma'], ['\\Delta'], ['\\Theta'], ['\\Lambda'], ['\\Xi'], ['\\Pi'], ['\\Sigma'], ['\\Upsilon'],
      ['\\Phi'], ['\\Psi'], ['\\Omega'],
    ],
  },
  {
    id: 'calculus',
    label: 'Giải tích',
    items: [
      ['\\lim_{{} \\to {}}', 'Giới hạn'],
      ['\\lim_{x \\to 0}', 'Giới hạn x → 0'],
      ['\\lim_{x \\to \\infty}', 'Giới hạn x → ∞'],
      ['\\lim_{x \\to {}^{+}}', 'Giới hạn phải'],
      ['\\lim_{x \\to {}^{-}}', 'Giới hạn trái'],
      ['\\sum_{{}}^{{}}', 'Tổng'],
      ['\\sum_{i=1}^{n}', 'Tổng i = 1 → n'],
      ['\\prod_{{}}^{{}}', 'Tích'],
      ['\\int {} \\, dx', 'Nguyên hàm'],
      ['\\int_{{}}^{{}} {} \\, dx', 'Tích phân xác định'],
      ['\\iint_{D} {} \\, dA', 'Tích phân kép'],
      ['\\iiint_{V} {} \\, dV', 'Tích phân bội ba'],
      ['\\oint_{C} {} \\, ds', 'Tích phân đường khép kín'],
      ['\\left. {} \\right|_{{}}^{{}}', 'Thế cận'],
      ["f'(x)", 'Đạo hàm cấp 1'],
      ["f''(x)", 'Đạo hàm cấp 2'],
      ['f^{(n)}(x)', 'Đạo hàm cấp n'],
      ['\\frac{d}{dx}', 'Toán tử đạo hàm'],
      ['\\frac{dy}{dx}', 'dy/dx'],
      ['\\frac{d^2y}{dx^2}', 'Đạo hàm cấp 2 (Leibniz)'],
      ['\\frac{\\partial {}}{\\partial {}}', 'Đạo hàm riêng'],
      ['\\partial', 'Ký hiệu đạo hàm riêng'],
      ['\\nabla', 'Nabla (gradient)'],
      ['\\Delta x', 'Số gia'],
      ['dx'],
      ['e^{}', 'Hàm mũ cơ số e'],
      ['\\exp\\left( {} \\right)', 'exp'],
      ['\\ln {}', 'Logarit tự nhiên'],
      ['\\log {}', 'Logarit'],
      ['\\log_{{}} {}', 'Logarit cơ số a'],
      ['\\sin {}'], ['\\cos {}'], ['\\tan {}'], ['\\cot {}'],
      ['\\sin^2 {}', 'sin bình phương'],
      ['\\arcsin {}'], ['\\arccos {}'], ['\\arctan {}'],
      ['\\sinh {}'], ['\\cosh {}'], ['\\tanh {}'],
      ['\\max'], ['\\min'], ['\\sup'], ['\\inf'],
      ['\\operatorname{sgn} {}', 'Hàm dấu'],
    ],
  },
  {
    id: 'sets',
    label: 'Tập hợp · Logic',
    items: [
      ['\\in', 'Thuộc'],
      ['\\notin', 'Không thuộc'],
      ['\\ni', 'Chứa phần tử'],
      ['\\subset', 'Tập con thực sự'],
      ['\\subseteq', 'Tập con'],
      ['\\supset', 'Chứa (tập cha)'],
      ['\\supseteq', 'Chứa hoặc bằng'],
      ['\\cup', 'Hợp'],
      ['\\cap', 'Giao'],
      ['\\setminus', 'Hiệu hai tập hợp'],
      ['\\bigcup_{{}}^{{}}', 'Hợp nhiều tập'],
      ['\\bigcap_{{}}^{{}}', 'Giao nhiều tập'],
      ['\\emptyset', 'Tập rỗng'],
      ['\\varnothing', 'Tập rỗng (kiểu khác)'],
      ['\\{ {} \\}', 'Tập hợp liệt kê'],
      ['\\{ x \\mid {} \\}', 'Tập hợp theo tính chất'],
      ['\\mathbb{N}', 'Số tự nhiên'],
      ['\\mathbb{N}^*', 'Số tự nhiên khác 0'],
      ['\\mathbb{Z}', 'Số nguyên'],
      ['\\mathbb{Q}', 'Số hữu tỉ'],
      ['\\mathbb{R}', 'Số thực'],
      ['\\mathbb{C}', 'Số phức'],
      ['[{} ; {}]', 'Đoạn'],
      ['({} ; {})', 'Khoảng'],
      ['\\forall', 'Với mọi'],
      ['\\exists', 'Tồn tại'],
      ['\\nexists', 'Không tồn tại'],
      ['\\neg', 'Phủ định'],
      ['\\overline{A}', 'Phủ định / phần bù'],
      ['\\land', 'Và'],
      ['\\lor', 'Hoặc'],
      ['\\Rightarrow', 'Suy ra'],
      ['\\Leftarrow', 'Được suy ra từ'],
      ['\\Leftrightarrow', 'Tương đương'],
      ['\\iff', 'Khi và chỉ khi'],
      ['\\therefore', 'Do đó'],
      ['\\because', 'Vì'],
      ['\\perp', 'Vuông góc'],
      ['\\parallel', 'Song song'],
      ['\\angle', 'Góc'],
      ['\\widehat{ABC}', 'Góc ABC'],
      ['\\triangle', 'Tam giác'],
      ['\\sim', 'Đồng dạng'],
      ['\\cong', 'Bằng nhau (hình)'],
      ['\\propto', 'Tỉ lệ thuận'],
      ['\\mid', 'Chia hết'],
      ['\\nmid', 'Không chia hết'],
      ['{} \\equiv {} \\pmod{{}}', 'Đồng dư'],
    ],
  },
  {
    id: 'arrows',
    label: 'Mũi tên',
    items: [
      ['\\to', 'Tiến tới'],
      ['\\rightarrow'],
      ['\\leftarrow'],
      ['\\leftrightarrow'],
      ['\\longrightarrow'],
      ['\\Longrightarrow'],
      ['\\Longleftrightarrow'],
      ['\\mapsto', 'Ánh xạ'],
      ['\\uparrow'],
      ['\\downarrow'],
      ['\\updownarrow'],
      ['\\nearrow'],
      ['\\searrow'],
      ['\\rightleftharpoons', 'Phản ứng thuận nghịch'],
      ['\\xrightarrow{{}}', 'Mũi tên có chữ trên'],
      ['\\xleftarrow{{}}', 'Mũi tên trái có chữ'],
      ['\\hookrightarrow', 'Đơn ánh'],
      ['\\twoheadrightarrow', 'Toàn ánh'],
    ],
  },
  {
    id: 'structures',
    label: 'Ma trận · Hệ',
    items: [
      ['\\begin{pmatrix} {} & {} \\\\ {} & {} \\end{pmatrix}', 'Ma trận 2×2 (ngoặc tròn)'],
      ['\\begin{bmatrix} {} & {} & {} \\\\ {} & {} & {} \\\\ {} & {} & {} \\end{bmatrix}', 'Ma trận 3×3 (ngoặc vuông)'],
      ['\\begin{vmatrix} {} & {} \\\\ {} & {} \\end{vmatrix}', 'Định thức 2×2'],
      ['\\begin{vmatrix} {} & {} & {} \\\\ {} & {} & {} \\\\ {} & {} & {} \\end{vmatrix}', 'Định thức 3×3'],
      ['\\begin{pmatrix} {} \\\\ {} \\\\ {} \\end{pmatrix}', 'Vector cột'],
      ['\\begin{cases} {} \\\\ {} \\end{cases}', 'Hệ phương trình (2 dòng)'],
      ['\\begin{cases} {} \\\\ {} \\\\ {} \\end{cases}', 'Hệ phương trình (3 dòng)'],
      ['\\left[ \\begin{array}{l} {} \\\\ {} \\end{array} \\right.', 'Tuyển (hoặc)'],
      ['f(x) = \\begin{cases} {} & \\text{khi } {} \\\\ {} & \\text{khi } {} \\end{cases}', 'Hàm nhiều nhánh'],
      ['\\begin{aligned} {} &= {} \\\\ &= {} \\end{aligned}', 'Biến đổi nhiều dòng thẳng hàng'],
      ['\\binom{{}}{{}}', 'Tổ hợp (nhị thức)'],
      ['C_{{}}^{{}}', 'Tổ hợp C'],
      ['A_{{}}^{{}}', 'Chỉnh hợp A'],
      ['A^{T}', 'Ma trận chuyển vị'],
      ['A^{-1}', 'Ma trận nghịch đảo'],
      ['\\det(A)', 'Định thức'],
      ['\\vec{u} \\cdot \\vec{v}', 'Tích vô hướng'],
      ['\\vec{u} \\times \\vec{v}', 'Tích có hướng'],
      ['|\\vec{u}|', 'Độ dài vector'],
    ],
  },
  {
    id: 'templates',
    label: 'Mẫu công thức',
    items: [
      ['x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}', 'Nghiệm phương trình bậc hai'],
      ['\\Delta = b^2 - 4ac', 'Biệt thức Delta'],
      ['x_1 + x_2 = -\\frac{b}{a}, \\quad x_1 x_2 = \\frac{c}{a}', 'Định lý Vi-ét'],
      ['a^2 + b^2 = c^2', 'Định lý Pytago'],
      ['(a + b)^2 = a^2 + 2ab + b^2', 'Hằng đẳng thức (a + b)²'],
      ['a^2 - b^2 = (a - b)(a + b)', 'Hiệu hai bình phương'],
      ['(a + b)^n = \\sum_{k=0}^{n} \\binom{n}{k} a^{n-k} b^{k}', 'Nhị thức Newton'],
      ['C_n^k = \\frac{n!}{k!\\,(n-k)!}', 'Số tổ hợp'],
      ['A_n^k = \\frac{n!}{(n-k)!}', 'Số chỉnh hợp'],
      ['S_n = \\frac{n(u_1 + u_n)}{2}', 'Tổng cấp số cộng'],
      ['S_n = u_1 \\frac{1 - q^n}{1 - q}', 'Tổng cấp số nhân'],
      ["f'(x) = \\lim_{h \\to 0} \\frac{f(x+h) - f(x)}{h}", 'Định nghĩa đạo hàm'],
      ["(uv)' = u'v + uv'", 'Đạo hàm tích'],
      ["\\left( \\frac{u}{v} \\right)' = \\frac{u'v - uv'}{v^2}", 'Đạo hàm thương'],
      ["(f \\circ g)'(x) = f'(g(x)) \\cdot g'(x)", 'Đạo hàm hàm hợp'],
      ['\\int_a^b f(x)\\,dx = F(b) - F(a)', 'Newton – Leibniz'],
      ['\\int u \\, dv = uv - \\int v \\, du', 'Tích phân từng phần'],
      ['\\lim_{x \\to 0} \\frac{\\sin x}{x} = 1', 'Giới hạn lượng giác cơ bản'],
      ['\\lim_{n \\to \\infty} \\left( 1 + \\frac{1}{n} \\right)^n = e', 'Giới hạn định nghĩa số e'],
      ['e^{i\\pi} + 1 = 0', 'Đồng nhất thức Euler'],
      ['\\sin^2 x + \\cos^2 x = 1', 'Hệ thức lượng giác cơ bản'],
      ['\\sin(a \\pm b) = \\sin a \\cos b \\pm \\cos a \\sin b', 'Công thức cộng (sin)'],
      ['\\cos(a \\pm b) = \\cos a \\cos b \\mp \\sin a \\sin b', 'Công thức cộng (cos)'],
      ['\\sin 2x = 2 \\sin x \\cos x', 'Nhân đôi (sin)'],
      ['\\cos 2x = \\cos^2 x - \\sin^2 x', 'Nhân đôi (cos)'],
      ['\\frac{a}{\\sin A} = \\frac{b}{\\sin B} = \\frac{c}{\\sin C} = 2R', 'Định lý sin'],
      ['a^2 = b^2 + c^2 - 2bc \\cos A', 'Định lý cosin'],
      ['\\log_a (xy) = \\log_a x + \\log_a y', 'Logarit của tích'],
      ['\\log_a x = \\frac{\\log_b x}{\\log_b a}', 'Đổi cơ số logarit'],
      ['d = \\sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}', 'Khoảng cách hai điểm'],
      ['d(M, \\Delta) = \\frac{|ax_0 + by_0 + c|}{\\sqrt{a^2 + b^2}}', 'Khoảng cách điểm tới đường thẳng'],
      ['(x - a)^2 + (y - b)^2 = R^2', 'Phương trình đường tròn'],
      ['S = \\pi r^2', 'Diện tích hình tròn'],
      ['V = \\frac{4}{3} \\pi r^3', 'Thể tích hình cầu'],
      ['S = \\frac{1}{2} a h', 'Diện tích tam giác'],
      ['P(A \\cup B) = P(A) + P(B) - P(A \\cap B)', 'Xác suất hợp'],
      ['P(A \\mid B) = \\frac{P(B \\mid A)\\,P(A)}{P(B)}', 'Công thức Bayes'],
      ['E(X) = \\sum_{i} x_i \\, p_i', 'Kỳ vọng'],
      ['\\bar{x} = \\frac{1}{n} \\sum_{i=1}^{n} x_i', 'Trung bình cộng'],
      ['s^2 = \\frac{1}{n} \\sum_{i=1}^{n} (x_i - \\bar{x})^2', 'Phương sai'],
      ['z = a + bi, \\quad |z| = \\sqrt{a^2 + b^2}', 'Số phức và môđun'],
      ['F = ma', 'Định luật II Newton'],
      ['v = v_0 + at', 'Vận tốc chuyển động biến đổi đều'],
      ['s = v_0 t + \\frac{1}{2} a t^2', 'Quãng đường chuyển động biến đổi đều'],
      ['E = mc^2', 'Năng lượng – khối lượng'],
      ['W_{\\text{đ}} = \\frac{1}{2} m v^2', 'Động năng'],
      ['I = \\frac{U}{R}', 'Định luật Ôm'],
      ['PV = nRT', 'Phương trình khí lí tưởng'],
    ],
  },
]

/** Chuỗi hiển thị trên nút: ô `{}` cần điền vẽ thành □. */
// Khoảng trắng render ra vô hình -> vẽ 2 ô □ cách nhau đúng khoảng đó để nút không bị trống.
const SPACING_DISPLAY = { '\\quad': '\\square\\quad\\square', '\\,': '\\square\\,\\square' }

export function snippetDisplay(latex) {
  if (SPACING_DISPLAY[latex]) return SPACING_DISPLAY[latex]
  // \text{} là chế độ chữ (không dùng được \square) -> hiện chữ mẫu.
  return latex.replace(/\\text\{\}/g, '\\text{abc}').replace(/\{\}/g, '{\\square}')
}

/** Vị trí đặt con trỏ sau khi chèn: vào trong `{}` đầu tiên, không có thì cuối đoạn chèn. */
export function snippetCaret(latex) {
  const i = latex.indexOf('{}')
  return i >= 0 ? i + 1 : latex.length
}
